[build]
  command = "npm ci && npm run build:client"  # build from repo root, client only
  publish = "dist"                            # we output to /dist (repo root)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
